 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace S2C
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID JoinClient = (Nettention.Proud.RmiID)2000+1;
			public const Nettention.Proud.RmiID LeaveClient = (Nettention.Proud.RmiID)2000+2;
			public const Nettention.Proud.RmiID EntityAppear = (Nettention.Proud.RmiID)2000+3;
			public const Nettention.Proud.RmiID EntityDisappear = (Nettention.Proud.RmiID)2000+4;
			public const Nettention.Proud.RmiID MoveTo = (Nettention.Proud.RmiID)2000+5;
			public const Nettention.Proud.RmiID MoveToArray = (Nettention.Proud.RmiID)2000+6;
			public const Nettention.Proud.RmiID CheckLatency = (Nettention.Proud.RmiID)2000+7;
			public const Nettention.Proud.RmiID EntityCount = (Nettention.Proud.RmiID)2000+8;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			JoinClient,
			LeaveClient,
			EntityAppear,
			EntityDisappear,
			MoveTo,
			MoveToArray,
			CheckLatency,
			EntityCount,
		};
	}
}






				 
